# Generated by Django 2.2.6 on 2020-07-02 09:01

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200702_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
